### PR TITLE
feat: add subsidy type (complete)

### PR DESCRIPTION
**Pull request by xdumaine**
needs marketplace PR and schema regen

### CODE REVIEW

**Review by 0xch4z — APPROVED** [review]
Lgtm

**Comment by xdumaine** [comment]
@0xch4z can you help me with the regeneration stuff (I manually deployed the marketplace changes to dev, but it's not merged yet).

**Comment by 0xch4z** [comment]
> @0xch4z can you help me with the regeneration stuff (I manually deployed the marketplace changes to dev, but it's not merged yet).

I'm out of town right now but I'll look into this tomorrow night when I'm back at my work computer. 👍

**Comment by xdumaine** [comment]
Yeah no worries on the weekend for sure, I'm just working today because I'm planning a little time out this week.

**Comment by SchaeStewart** [comment]
@0xch4z you'll have to approve this one since Xander and I both have commits

**Review by 0xch4z — APPROVED** [review]

**Pull request merged**
